sudo: required
services:
    - docker

before_install:
    - docker build -t dagudelo/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true dagudelo/react-test npm test  -- --coverage
after_success:
    - docker build -t dagudelo/multi-client ./client
    - docker build -t dagudelo/multi-nginx ./nginx
    - docker build -t dagudelo/multi-server ./server
    - docker build -t dagudelo/multi-worker ./worker
    # log in docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dagudelo/multi-client
    - docker push dagudelo/multi-nginx
    - docker push dagudelo/multi-server
    - docker push dagudelo/multi-worker
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: multiDocker-env
    env: MultidockerEnv-env
    bucket_name : elasticbeanstalk-us-east-2-581380737030
    bucket_path : docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secret: $AWS_SECRET_KEY
