
version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
     - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./server:/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    volumes:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - '3050:80' 
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
