verision: '3'
services:
  postgres:
    image: 'postgres/lastest'
  redis:
    image: 'redis/lastest'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volume:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./server:/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

