version: '3'
services:
  postgres:
    image: 'postgres/lastest'
  redis:
    image: 'redis/lastest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80' 
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./server:/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./client:/app 
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      # not copy the node modules
      - /app/node_modules 
      # everything in the server folder will be referenced by the container in /app
      - ./worker:/app

